# Generated by Django 5.0.4 on 2024-04-24 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
