# Generated by Django 5.0.4 on 2024-04-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_note_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='author',
            new_name='author_id',
        ),
        migrations.AddField(
            model_name='note',
            name='author_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
