# Generated by Django 5.0.4 on 2024-04-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_author_note_author_id_note_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='author_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
